name: test-react-native-app
on:
  push:
    branches:
      - master
jobs:
  temp:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo "Hello!"
  # setup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: install
  #       run: |
  #         npm install
  # test:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: run tests
  #       run: |
  #         npm test
