name: test-react-native-app
on:
  push:
    branches:
      - master
jobs:
  temp:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo "Hello!"
      - name: test
        run: |
          npm install && npm test
