name: test-react-native-app
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          npm install
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: |
          npm test
